version: '3.8'

services:
  db:
    image: postgres:16
    container_name: local_postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"

  app:
    image: acrwebappstaging3216787432.azurecr.io/webapp:latest
    container_name: local_flask_app
    environment:
      AZURE_POSTGRESQL_HOST: db
      AZURE_POSTGRESQL_NAME: testdb
      AZURE_POSTGRESQL_USER: testuser
      AZURE_POSTGRESQL_PASSWORD: testpass
      POSTGRES_PORT: 5432
    depends_on:
      - db
    ports:
      - "5000:5000"