name: Build and deploy Python app to Azure Web App

on:
  # push:
  #   branches:
  #     - feature/fourthtask
  workflow_dispatch:

env:
  APP_NAME: "app-webapp-staging-3216787432"
  ACR_NAME: "acrwebappstaging3216787432"
  IMAGE_NAME: "webapp"
  IMAGE_TAG: "v1"

jobs:
  terraform:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.4

      - name: Terraform Init
        run: terraform init
        working-directory: ./tf-app/staging/core

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./tf-app/staging/core

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./tf-app/staging/core
        
  build:
    runs-on: ubuntu-latest
    needs: terraform
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.ACR_NAME }}.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f Dockerfile .

      - name: Push Docker image to ACR
        run: docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.APP_NAME }}
          images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Wait for app to start
        run: sleep 40

      - name: Check DB health endpoint
        run: |
          curl -sf https://"$APP_NAME".azurewebsites.net/db-health